### ISSUE TITLE
Request to add a License

### ISSUE THREAD

**Issue by anmabu** [MichielStock/DiffDynProg.jl#6]
Hi Michiel, 

I just found your project on GitHub and find it incredibly interesting. I noticed that it currently lacks a license. Adding a licence to your project will clarify how others can use/modify/distribute the code you've made public. You did a great job in this project and it'd be a shame not to put your work to use. 

I'm working on a project in Julia where we want to do differentiable sequence alignment and being able to use your code would be an incredible help! 

Thanks in advance considering my request. 

Best regards, 
Anne

**Comment by MichielStock** [comment]
Hi Anne,

Thanks for your interest. I added an MIT licence. We spent a lot of work on this project (including a draft), but we got scooped before finishing it. I would be delighted if it would be of some use to someone. Feel free to contact me by mail if you want some additional material.

Kind regards,

Michiel
